'use strict';

module.exports = [
  {
    state: 'alabama',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'AL.com / The Birmingham News',
    url: 'https://www.al.com/',
  },
  {
    state: 'alaska',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Anchorage Daily News',
    url: 'https://www.adn.com/',
  },
  {
    state: 'arizona',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Arizona Republic',
    url: 'https://www.azcentral.com/',
  },
  {
    state: 'arizona',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Arizona)',
    url: 'https://journawiki.fandom.com/wiki/The_Arizona_Republic',
  },
  {
    state: 'arkansas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Arkansas Democrat-Gazette',
    url: 'https://www.arkansasonline.com/',
  },
  {
    state: 'arkansas',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Arkansas)',
    url: 'https://journawiki.fandom.com/wiki/Arkansas_Democrat-Gazette',
  },
  {
    state: 'colorado',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Denver Post',
    url: 'https://www.denverpost.com/',
  },
  {
    state: 'colorado',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Denver)',
    url: 'https://journawiki.fandom.com/wiki/The_Denver_Post',
  },
  {
    state: 'connecticut',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Hartford Courant',
    url: 'https://www.courant.com/',
  },
  {
    state: 'connecticut',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Connecticut)',
    url: 'https://journawiki.fandom.com/wiki/Hartford_Courant',
  },
  {
    state: 'delaware',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The News Journal (Wilmington)',
    url: 'https://www.delawareonline.com/',
  },
  {
    state: 'delaware',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Delaware)',
    url: 'https://journawiki.fandom.com/wiki/The_News_Journal',
  },
  {
    state: 'florida',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Miami Herald',
    url: 'https://www.miamiherald.com/',
  },
  {
    state: 'florida',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Florida)',
    url: 'https://journawiki.fandom.com/wiki/The_Miami_Herald',
  },
  {
    state: 'georgia',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Atlanta Journal-Constitution',
    url: 'https://www.ajc.com/',
  },
  {
    state: 'georgia',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Georgia)',
    url: 'https://journawiki.fandom.com/wiki/The_Atlanta_Journal-Constitution',
  },
  {
    state: 'hawaii',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Honolulu Star-Advertiser',
    url: 'https://www.staradvertiser.com/',
  },
  {
    state: 'hawaii',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Hawaii)',
    url: 'https://journawiki.fandom.com/wiki/Honolulu_Star-Advertiser',
  },
  {
    state: 'idaho',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Idaho Statesman',
    url: 'https://www.idahostatesman.com/',
  },
  {
    state: 'illinois',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Chicago Tribune',
    url: 'https://www.chicagotribune.com/',
  },
  {
    state: 'illinois',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Illinois)',
    url: 'https://journawiki.fandom.com/wiki/Chicago_Tribune',
  },
  {
    state: 'indiana',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Indianapolis Star',
    url: 'https://www.indystar.com/',
  },
  {
    state: 'indiana',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Indiana)',
    url: 'https://journawiki.fandom.com/wiki/The_Indianapolis_Star',
  },
  {
    state: 'iowa',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Des Moines Register',
    url: 'https://www.desmoinesregister.com/',
  },
  {
    state: 'iowa',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Iowa)',
    url: 'https://journawiki.fandom.com/wiki/The_Des_Moines_Register',
  },
  {
    state: 'kansas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Wichita Eagle',
    url: 'https://www.kansas.com/',
  },
  {
    state: 'kansas',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Kansas)',
    url: 'https://journawiki.fandom.com/wiki/The_Wichita_Eagle',
  },
  {
    state: 'kentucky',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Courier-Journal (Louisville)',
    url: 'https://www.courier-journal.com/',
  },
  {
    state: 'kentucky',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Kentucky)',
    url: 'https://journawiki.fandom.com/wiki/The_Courier-Journal',
  },
  {
    state: 'louisiana',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Times-Picayune / New Orleans Advocate',
    url: 'https://www.nola.com/',
  },
  {
    state: 'louisiana',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Louisiana)',
    url: 'https://journawiki.fandom.com/wiki/The_Times-Picayune',
  },
  {
    state: 'maine',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Portland Press Herald',
    url: 'https://www.pressherald.com/',
  },
  {
    state: 'maryland',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Baltimore Sun',
    url: 'https://www.baltimoresun.com/',
  },
  {
    state: 'maryland',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Maryland)',
    url: 'https://journawiki.fandom.com/wiki/The_Baltimore_Sun',
  },
  {
    state: 'massachusetts',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Boston Globe',
    url: 'https://www.bostonglobe.com/',
  },
  {
    state: 'massachusetts',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Massachusetts)',
    url: 'https://journawiki.fandom.com/wiki/The_Boston_Globe',
  },
  {
    state: 'michigan',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Detroit Free Press',
    url: 'https://www.freep.com/',
  },
  {
    state: 'minnesota',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Minnesota Star Tribune',
    url: 'https://www.startribune.com/',
  },
  {
    state: 'mississippi',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Clarion-Ledger (Jackson)',
    url: 'https://www.clarionledger.com/',
  },
  {
    state: 'mississippi',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Mississippi)',
    url: 'https://journawiki.fandom.com/wiki/The_Clarion-Ledger',
  },
  {
    state: 'missouri',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'St. Louis Post-Dispatch',
    url: 'https://www.stltoday.com/',
  },
  {
    state: 'missouri',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Missouri)',
    url: 'https://journawiki.fandom.com/wiki/St._Louis_Post-Dispatch',
  },
  {
    state: 'montana',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Missoulian',
    url: 'https://missoulian.com/',
  },
  {
    state: 'montana',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Billings Gazette',
    url: 'https://billingsgazette.com/',
  },
  {
    state: 'nebraska',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Omaha World-Herald',
    url: 'https://omaha.com/',
  },
  {
    state: 'nebraska',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Nebraska)',
    url: 'https://journawiki.fandom.com/wiki/Omaha_World-Herald',
  },
  {
    state: 'nevada',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Las Vegas Review-Journal',
    url: 'https://www.reviewjournal.com/',
  },
  {
    state: 'nevada',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Nevada)',
    url: 'https://journawiki.fandom.com/wiki/Las_Vegas_Review-Journal',
  },
  {
    state: 'new-hampshire',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'New Hampshire Union Leader (Manchester)',
    url: 'https://www.unionleader.com/',
  },
  {
    state: 'new-jersey',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Star-Ledger (NJ.com)',
    url: 'https://www.nj.com/starledger/',
  },
  {
    state: 'new-jersey',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (New Jersey)',
    url: 'https://journawiki.fandom.com/wiki/The_Star-Ledger',
  },
  {
    state: 'new-mexico',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Albuquerque Journal',
    url: 'https://www.abqjournal.com/',
  },
  {
    state: 'new-york',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The New York Times',
    url: 'https://www.nytimes.com/',
  },
  {
    state: 'new-york',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Newsday',
    url: 'https://www.newsday.com/',
  },
  {
    state: 'north-carolina',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Charlotte Observer',
    url: 'https://www.charlotteobserver.com/',
  },
  {
    state: 'north-dakota',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Bismarck Tribune',
    url: 'https://bismarcktribune.com/',
  },
  {
    state: 'ohio',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Plain Dealer (Cleveland.com)',
    url: 'https://www.cleveland.com/',
  },
  {
    state: 'oklahoma',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Oklahoman',
    url: 'https://www.oklahoman.com/',
  },
  {
    state: 'oregon',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Oregonian (OregonLive)',
    url: 'https://www.oregonlive.com/',
  },
  {
    state: 'pennsylvania',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Philadelphia Inquirer',
    url: 'https://www.inquirer.com/',
  },
  {
    state: 'rhode-island',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Providence Journal',
    url: 'https://www.providencejournal.com/',
  },
  {
    state: 'south-carolina',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Post and Courier (Charleston)',
    url: 'https://www.postandcourier.com/',
  },
  {
    state: 'south-dakota',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Argus Leader (Sioux Falls)',
    url: 'https://www.argusleader.com/',
  },
  {
    state: 'tennessee',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Tennessean (Nashville)',
    url: 'https://www.tennessean.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Dallas Morning News',
    url: 'https://www.dallasnews.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Houston Chronicle',
    url: 'https://www.houstonchronicle.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'San Antonio Express-News',
    url: 'https://www.expressnews.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Austin American-Statesman',
    url: 'https://www.statesman.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Fort Worth Star-Telegram',
    url: 'https://www.star-telegram.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'El Paso Times',
    url: 'https://www.elpasotimes.com/',
  },
  {
    state: 'texas',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Texas Tribune',
    url: 'https://www.texastribune.org/',
  },
  {
    state: 'utah',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Deseret News',
    url: 'https://www.deseret.com/',
  },
  {
    state: 'utah',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Salt Lake Tribune',
    url: 'https://www.sltrib.com/',
  },
  {
    state: 'vermont',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Burlington Free Press',
    url: 'https://www.burlingtonfreepress.com/',
  },
  {
    state: 'virginia',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Virginian-Pilot (Norfolk)',
    url: 'https://www.pilotonline.com/',
  },
  {
    state: 'virginia',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Richmond Times-Dispatch',
    url: 'https://richmond.com/',
  },
  {
    state: 'washington',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Seattle Times',
    url: 'https://www.seattletimes.com/',
  },
  {
    state: 'washington',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Washington)',
    url: 'https://journawiki.fandom.com/wiki/The_Seattle_Times',
  },
  {
    state: 'west-virginia',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'The Charleston Gazette-Mail',
    url: 'https://www.wvgazettemail.com/',
  },
  {
    state: 'wisconsin',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Milwaukee Journal Sentinel',
    url: 'https://www.jsonline.com/',
  },
  {
    state: 'wisconsin',
    type: 'news_bulletin',
    strategy: 'dynamicBulletin',
    name: 'Journawiki - Fandom (Wisconsin)',
    url: 'https://journawiki.fandom.com/wiki/Milwaukee_Journal_Sentinel',
  },
  {
    state: 'wyoming',
    type: 'news_bulletin',
    strategy: 'staticBulletin',
    name: 'Casper Star-Tribune',
    url: 'https://trib.com/',
  },
];
